theme: jekyll-theme-minimal
title: Austin Miller
description: I'm an experienced entrepreneur and full-stack developer. I do custom application development and am the creator of PagerTree.
# logo: /assets/img/logo.png